import { Link, createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/')({ component: Home })

function Home() {
  return (
    <div className="mx-auto max-w-2xl p-8">
      <h1 className="text-4xl font-bold">Welcome to TanStack Start</h1>
      <p className="mt-4 text-lg text-gray-600">
        Generated by create-softeneers-app. A fullstack React app with type-safe server functions.
      </p>
      <div className="mt-6 flex flex-wrap gap-3">
        <Link to="/cars" className="rounded bg-black px-5 py-2.5 font-medium text-white">
          Cars CRUD demo →
        </Link>
        {/* #if auth */}
        <Link to="/login" className="rounded border border-gray-300 px-5 py-2.5 font-medium">
          Sign in
        </Link>
        {/* #endif */}
        {/* #if payments */}
        <Link to="/billing" className="rounded border border-gray-300 px-5 py-2.5 font-medium">
          Billing
        </Link>
        {/* #endif */}
      </div>
    </div>
  )
}
